### ISSUE TITLE
Nginx sendfile && Virtualbox

### ISSUE THREAD

**Issue by risdenk** [fanghuang/Predicting-Hot-Technology-Trends#4]
http://docs.vagrantup.com/v2/synced-folders/virtualbox.html

**Comment by coreyja** [comment]
@risdenk Do you know what this sendfile parameter does? I'm just curious. The code snippet I got the nginx role from had it turned on so that's why I had it like that.

**Comment by risdenk** [comment]
@coreyja No idea actually. Just that I knew it was in the Vagrant Virtualbox documentation :)
